import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#f8f9fa" },
  header: {
    paddingTop: 60,
    paddingHorizontal: 20,
    paddingBottom: 20,
    backgroundColor: "#fff",
    borderBottomWidth: 1,
    borderBottomColor: "#eee",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  workoutName: { fontSize: 16, fontWeight: "bold", width: "70%" },
  timer: {
    fontSize: 18,
    fontWeight: "700",
    color: "#007AFF",
    fontFamily: "monospace",
  },
  exerciseList: { padding: 15 },
  exerciseCard: {
    backgroundColor: "#fff",
    padding: 16,
    borderRadius: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "#eee",
  },
  activeCard: {
    borderColor: "#007AFF",
    borderWidth: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  exerciseHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 6,
  },
  exerciseTitle: { fontSize: 16, fontWeight: "bold" },
  badge: {
    backgroundColor: "#E3F2FD",
    color: "#007AFF",
    fontSize: 12,
    fontWeight: "600",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  exerciseDetails: { fontSize: 14, color: "#666" },
  footer: {
    padding: 20,
    backgroundColor: "#fff",
    borderTopWidth: 1,
    borderTopColor: "#eee",
    marginBottom: 20,
  },
  centered: { alignItems: "center", marginTop: 40 },
  // Styles for series
  seriesContainer: {
    marginTop: 15,
  },
  serieRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
  },
  serieNumber: {
    fontWeight: "bold",
    width: "10%",
    textAlign: "center",
  },
  previousPerformance: {
    color: "#888",
    width: "25%",
    textAlign: "center",
  },
  serieInput: {
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 4,
    width: "18%",
    textAlign: "center",
  },
  seriesActions: {
    flexDirection: "row",
    justifyContent: "space-around",
    marginTop: 15,
  },
  actionButton: {
    backgroundColor: "#007AFF",
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderRadius: 8,
  },
  actionButtonText: {
    color: "#fff",
    fontWeight: "bold",
  },
  removeButton: {
    backgroundColor: "#FF3B30",
  },
  seriesHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 5,
    paddingHorizontal: 5,
  },
  headerText: {
    fontWeight: 'bold',
    fontSize: 12,
    color: '#555',
    textAlign: 'center',
  },
});
